### ISSUE TITLE
Using digital encode instead of control vinyl

### ISSUE THREAD

**Issue by bobkruijer** [pideck/pideck#102]
Hi, I've gone through the previous issues, and other builds, to see if a digital encoder has been used to actually substitute the control vinyl. It looks like encoders have been implemented/suggested for e.g. track selection but not for the control signal. Is that correct?

If it can already be used, which gpios can be used, and what kind of input do they expect?

**Comment by danielhjames** [comment]
Hi, that is correct. The timecode control signal is audio data via a USB or I2S soundcard. Generally the I2S soundcards such as http://www.audioinjector.net/rpi-hat use the HAT format and mount directly on the GPIO pins.

It is possible to replace the vinyl or CD using a WAV file containing timecode, but then you need a device to play the WAV file into the soundcard of the PiDeck. I understand that this is how the base unit of the Phase accelerometer system works: https://mwm-store.com/phase

If you could describe what you have in mind, I'll see if I can make any helpful suggestions!

**Comment by bobkruijer** [comment]
Thanks for your answer. I don't want to use another way to push timecode 'in', but rather was wondering if I could use another digital signal (encoder or voltage for example) to dictate the direction and speed of the audio. In other words, no timecode decoding needed. Does that make more sense?

BTW, that is not exactly how Phase works. Phase synthesizes a tone, without position info, based on the gyroscope. The base unit just outputs a simple sinetone, that varies in frequency.

**Comment by danielhjames** [comment]
Hi @bobkruijer generally, DJ applications which don't use timecode use MIDI control or OSC. Please see also the [touchwax](https://github.com/oligau/touchwax) project by Olivier Gauthier.

Phase doesn't have position info of course, but that is similar to when using timecode in relative mode. We have yet to test Phase with xwax, let's see how reliable the Phase system turns out to be.

**Comment by brainlessboy** [comment]
is there any answer to this? i would be interested to do something similar, e.g. alternative device to control playback of audio based on speed and direction, some code examples to show how to produce/emulate the timecode sound procedurally or any other possible method would be cool :-)

**Comment by DubbyLabby** [comment]
It will require encoder support for the player object position, velocity, acceleration and so on... not difficult per se but a bit of work to do it standard since there are lots of encoder types in the market and midi commands attached to any of them.
Also motorized ones will add extra complexity layer... so I suspect it will be more useful choose first the encoder and code for that instead asking for universal support. Other option is going the opendeck platform route as retrofit kit for any encoder.

As a suggestion I will look into mixxx project and cheap china tablet as alternative or just an iPhone with djay pro. These aren’t so expensive in comparision, more powerful in each field and compatible.
Pideck is an amazing idea but too much focused in old school mixing. Even if you need scratching device sc1000 will be better project and encoder based instead xwax extra layer and pi linux gpio madness...
