### ISSUE TITLE
Unable to get to terminal without touchscreen

### ISSUE THREAD

**Issue by drj-io** [pideck/pideck#135]
Loving pideck, I have 2 builds. 1 without a touchscreen and one with a touchscreen. The one without a touchscreen I use an Ardiuno to emulate a keyboard.  I also have a wireless keyboard connected.  Here's that build: https://www.instagram.com/p/CTvHF1wr8zy/

Everything's mostly working great. However, I can't seem to figure out how to get to a terminal to adjust mixer settings to maximize volume out of my interface and reduce noise. From the docs, I see F-10 will "Open a terminal (only when touch buttons are in focus)".  Obviously, the touch buttons are never in focus because I'm using a keyboard. Any way around this? I've tried to Ctrl-C at boot etc.  

Cheers!

**Comment by danielhjames** [comment]
Hi @drj-io nice project! The feature to open a terminal is a hack, using the touch button code (which is why the buttons must be in focus for this to work). You can see how we did this on line 130 of the script https://github.com/pideck/pideck/blob/master/touchscreen_controls_R

If you are not using these touchscreen buttons, because xwax has no touch support, you can hack our touchscreen_controls scripts to make a terminal launcher without any visible buttons. As long as it is started with the right focus it should stay available to the user. The issue with touchscreen focus is that people tap the xwax window expecting something to happen, and then our extra buttons lose focus.

**Comment by drj-io** [comment]
Thanks for the reply! I think I'll just use SSH over IP to manage and put a Cat5 jack on the back of the turntable. I think that will let me do what I need to.  

Thanks for your help!
