### ISSUE TITLE
Bypass button in GUI

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#44]
Add a button to enable the bypass function of any soundcard plugged in.

**Comment by BennPaul** [comment]
First try:
I just added a new button in one of the touchscreen_controls_-files:


> def bypass_button(widget, data):
    if widget.get_active():
       os.system("amixer sset 'Output Mixer Line Bypass' off")
    else:
       os.system("amixer sset 'Output Mixer Line Bypass' on")

It is working with audioinjector.

Before bypassing one must stop playing music in xwax and press the TIMECD button, otherwise xwax ist still trying to play the loaded tune.

For switching back to DVS press both buttons again.

See a picture at issue #43

**Comment by danielhjames** [comment]
Thanks! I can think of three useful states for combination of these two controls:

1. Timecode on, bypass off
2. Timecode off, bypass off (for DVS when changing vinyl, cleaning/changing the stylus)
3. Timecode off, bypass on (for analogue vinyl)

The other possibility of timecode on, bypass on, seems like something we should avoid by design, so there is never any chance of sending the analogue vinyl signal to xwax.  So I guess the timecode button could remain independent, but the bypass button use amixer and also ensure the correct timecode option in xwax.

For example, playing a DVS tune, the user switches off timecode in xwax as they know the next selection on that deck will be analogue. After mixing to the other deck and taking off the timecode vinyl, they tap the bypass button. If the bypass button simply toggles the timecode control in xwax, it will switch it back on, which is not what the user wants. So the bypass control needs to know the current state of the timecode control. Should we set a variable in the script for this?

It would be great to have xwax send a notification when it detects timecode that we could use to switch off bypass automatically. Could save some embarrassment :-)

**Comment by BennPaul** [comment]
> So the bypass control needs to know the current state of the timecode control. Should we set a variable in the script for this?

Yes!

> It would be great to have xwax send a notification when it detects timecode that we could use to switch off bypass automatically. Could save some embarrassment :-)

Sounds really good!!

**Comment by obbardc** [comment]
I've merged your PR for now :-)

For multiple soundcard support, I was thinking of a separate Python file for each soundcard to abstract it all out..

Cheers!

**Comment by danielhjames** [comment]
hmm, how about a flat-file database of soundcard parameters?

**Comment by obbardc** [comment]
Each card will have a different way of setting various things, so I don't
think a database would be the best way

A python file (about 20 lines) per card allows us to do all sorts of other
setting up like the setup of the dual channel controller we used for the
video.

The file wouldn't be very complex either. I'll have a think on the best way
to do this...

Cheers!

**Comment by danielhjames** [comment]
Hi @BennPaul, Chris figured out the way to mute the ADC and DAC on the audioinjector so that you no longer have to stop xwax in bypass mode. See https://github.com/pideck/pideck/commit/4497c3ed7ad0b36282fe6e5c8fb0aa1ad3ab4072#diff-c567af6e845d51a0c1a0d1154e50ca00

**Comment by BennPaul** [comment]
@obbardc @danielhjames thank you! Really looking forward to 0.2.
