### ISSUE TITLE
Boot failure when USB stick is present

### ISSUE THREAD

**Issue by danielhjames** [pideck/pideck#50]
https://github.com/BennPaul reported that the PiDeck would not boot when a certain USB stick was inserted.

**Comment by BennPaul** [comment]
The usb stick is a san disk something with 32 gb, without any changes to the filesystem as out of the box. It reproducibly didn't boot with a usb cord extension for the stick plugged in to the bottom right usb port of the pi 3, with an old apple keyboard (with usb hub with logitech mouse receiver  connected) and an y-cable connected to the touchcontrol/power for the display. It only didn't boot with pideck. I unplugged everything yesterday, because I moved the arrangement. The usb stick was then on the upper left port and the keyboard was not connected. With this configuration it boots also with pideck. I just tested it with the keyboard plugged in again and tried all permutations of stick versus keyboard versus touchscreen, it always booted. Strange but I think this issue could be closed.

**Comment by danielhjames** [comment]
Thanks for the update!
