### ISSUE TITLE
Power supply

### ISSUE THREAD

**Issue by BennPaul** [pideck/pideck#53]
Wanted: 

One power supply for both a pi 3 and a phono preamp:

Raspberry pi 3 needs 5 V ca. 2.5 A
Behringer phono preamp needs 12 V ca. 150 mA

I tried an old hdd power supply from an icy box with 5 V / 2A  and 12 V / 2 A output.
The power for the pi 3 is not enough indicated by the yellow flash on the screen.

Is it better for this setting to use a step-up or step-down converter?
Can I integrate the icy box power supply or should I start with only 12 V or 5 V?

Thanks in advance!

**Comment by obbardc** [comment]
I would be weary of running both from the same power supply, switch mode
power supplies can be very noisy which could effect the phono preamp
output. Although this shouldn't really matter since we are using timecode.

The lightning bolt is fairly normal; as you are drawing so much current,
the input voltage in the Pi has dropped to probably about 4.9V which is
enough to se this warning off. The official Pi PSUs are regulated to 5.1V
so they will not droop below that 5V.

I would buy a step-down converter board from eBay, these have a little blue
pot to set the output voltage

**Comment by BennPaul** [comment]
Thank you very much for the tips!
