### ISSUE TITLE
Is it possible to use Pideck with "Numark Pt01 Scratch" or "Vestax Handy Trax" turntable soundcards?  

### ISSUE THREAD

**Issue by CircuitCirkus** [pideck/pideck#55]
Is it possible to use Pideck like this? https://www.youtube.com/watch?v=gG6wjcOcJv0&t=58s

**Comment by danielhjames** [comment]
You can use any turntable with stereo output, even a really bad one, see https://www.youtube.com/watch?v=2Fya9Cq2XTs

Using a USB output from the turntable depends on it being class compliant and having sufficient headroom for peaks in output (such as fast scratches or backspins). Otherwise you can use the analogue output.

We do not support Bluetooth mini crossfaders as there is no mixer in the PiDeck. Any analogue mixer will work, and should add no latency.
