### ISSUE TITLE
USB Controller

### ISSUE THREAD

**Issue by RobNFrank** [pideck/pideck#56]
Hey guys, is it possible to use PiDeck with a Hercules USB Controller instead of USB Vinyl?

**Comment by danielhjames** [comment]
Hi, if the Hercules controller includes a class-compliant USB audio interface with a phono pre-amp, it will work with control vinyl. I have an old Hercules Mk2 controller like this which works fine with the PiDeck.

**Comment by DubbyLabby** [comment]
I think the question was around implementing usb controller jogwheel instead timecode.
Maybe merging some files from Rasteri/sc1000 could be a start point... someone?

I can point the job but I'm not a coder myself and less linux savy...

**Comment by danielhjames** [comment]
@DubbyLabby for people that don't want to use timecode, mixxx is your friend! https://mixxx.org/news/2020-08-22-portable-mixxx-setup/

**Comment by DubbyLabby** [comment]
Who said I don't want timecode or I didn't try the Mixxx route?
Everytime someone request this and you point to the same place is just not listening carefully... btw Mixxx has its own struggles and I prefer the PiDeck approach.

I will edit to be more clear. I'm just done with PiDeck/Mixxx thanks to this "common mantra about Mixxx for controllers".
 I will go the DjPlayer route and get both. Old iPhones are cheaper than raspis with screen and I don't need to install the whole OS and debug it etc. Shame since I wanted to contribute with these projects but lack of vision makes them just a no-go.
 Thanks anyways for your work and supporting these who just need a dvs solution on pi...
