### ISSUE TITLE
Bypass for UFO202?

### ISSUE THREAD

**Issue by sempixel** [pideck/pideck#78]
Hey,

Will the new bypass feature be compatible with Behringer UFO202?

Thanks!

**Comment by sempixel** [comment]
As seen [here](http://djtechtools.com/2018/06/06/pideck-0-2-coming-soon-any-old-cdj-raspberry-pi-a-standalone-deck/)

> There’s also a bypass feature that allows users with certain soundcards…

It needs clarification.

Thanks.

**Comment by obbardc** [comment]
Hi @danielhjames  can you try this out on the UFO202?

Chris

**Comment by danielhjames** [comment]
Hi @sempixel thanks for your question! I do not have a UFO202 for testing at the moment, but I suspect its codec might not have a bypass feature in hardware. On the circuit board the analogue input is hard wired to the analogue output, which is why some people cut those traces in order to use these devices with digital vinyl software. See https://mixxx.org/forums/viewtopic.php?t=2438 or https://www.youtube.com/watch?v=iYIiqVGjcVk (skip to 4:00).

The diagram on the data sheet for the codec I think the UFO202 device contains (page 9 of http://www.ti.com/lit/ds/symlink/pcm2900.pdf) shows no direct audio path from ADC to DAC that I can see, which I guess is why this bypass was hard wired on the circuit board. The Burr Brown PCM2900 (or similar TI codec) is used in other USB interfaces such as the American Audio Genie II which do not have the hard-wired bypass.

So if you want to use the UFO202 hardware, I guess your options are: make some kind of hardware mod to have a hardware bypass switch, rejoining those circuit board traces, or create a software bypass, maybe using jackd connections. Software bypass is not ideal because there will be an unnecessary round-trip through the ADC and DAC.
 
Trouble with the hardware mod would be find something on the circuit board large enough to solder to. It might introduce noise, but then older analogue amps have the signal passing through switches. So it could be possible but I'd recommend a different audio interface if hardware bypass is important to you.  

You might like to test the bypass controls on the Native Instruments Audio 8 or Audio 6 for example, as these devices are known to work with xwax. It might be possible to enable those bypass controls in alsamixer. A used example should cost about the same as the equivalent number of UFO202's.

Rest assured that if the PiDeck project releases an audio device, it will have hardware audio bypass :-)

**Comment by obbardc** [comment]
Is there any bypass function in the alsamixer?

If you could open it up and tell us the codec in the device then that would
give a better indication

Chris

**Comment by sempixel** [comment]
@obbardc I don't have any UFO202 at the moment, my question was asked to know better which audio interface should I buy.
I have two turntables, so 1x DVS or 2x? Audio Injector? UFO202? PiDeck 0.2? Etc…
If I buy a UFO202, and if nobody else do the test, I'll keep you updated.

I just need to choose now ;)

Thanks guys. All is clear.

**Comment by danielhjames** [comment]
For two turntables a used Native Instruments Audio 8 or Audio 4 could be a good choice in the short term, as these devices are known to work with xwax and you will be able to sell them on if they don't suit your needs.
null

**Comment by sempixel** [comment]
Okay. But does it support bypass? :)

I want to be able to switch between classic vinyls and DVS.
It's another element in the equation.

**Comment by danielhjames** [comment]
Native Instruments Audio devices do have a bypass feature, which is shown with an LED marked 'Thru' as I recall. I would suggest digging into the mixer code for the ALSA driver to confirm how it operates. Please let us know what you find out!

**Comment by danielhjames** [comment]
Known bypass status is listed at https://github.com/pideck/pideck/blob/master/soundcards.md
