### ISSUE TITLE
WHERE AM I GOING WRONG? - ATTEMPTING TO GET THE UMIX 44 SOUNDCARD TO WORK  IN 0.2 PIDECK

### ISSUE THREAD

**Issue by raynessupreme** [pideck/pideck#93]
A quick update regarding getting my Mixvibes Umix 44 Soundcard to work in the 0.2 release of Pideck.

The first positive is that it is detected in the /proc/asounds/cards file. However it is detected as a 0 (my dicer is detected as a 1) is this normal? Or should it be another number ?(1 or 2).

I added the card into the file /pideck/sup_cards.conf as Mivibes Umix 44 with an 04 on the end of the file (given the numbers on the end of the other files possibly represent the number of channels the soundcard has).

I then made the file /usr/share/pideck/umix44.asound.conf (is this the correct title to use?) - I added in the appropriate /.asoundrc file information as best I can. I attempted to write it how it should be spaced, its difficult not having a GUI desktop or  the opportunity to copy and paste a file into a folder, but I am attempting my best to learn in the Pideck CLI.

** said file is as follows** 

pcm.umix44_capture {
     type dsnoop
     ipc_key 1646
     slave {
         pcm "hw:Device"
         period_size 0
         buffer_size 65536
         rate 44100
         channels 4
     }
}

pcm.umix44_playback {
	type dmix
	ipc_key 1646
	slave {
		pcm "hw:Device"
		period_size 0
		buffer_size 65536
		rate 44100
		channels 4
	}
}

pcm.umix44_duplex {
	type asym
	playback.pcm umix44_playback
	capture.pcm umix44_capture
}

pcm.umix44_pair1 {
	type plug
	ttable.0.0 1.0
	ttable.1.1 1.0
	slave.pcm umix44_duplex
}

pcm.umix44_pair2 {
	type plug
	ttable.0.2 1.0
	ttable.1.3 1.0
	slave.pcm umix44_duplex
}

**

I have then opened up /usr/share/pideck/card_autodetect and added in what I thought was the appropriate coding to get my soundcard working (given I just imitated some of the other soundcard info already in the coding). 

This is as follows..

elif ( echo $CARDS_LINE_2 | grep -q “Mixvibes Umix 44” ) || ( echo$
         XCARD=”-a umix44_pair1 -a umix44_pair2”
         cp /usr/share/pideck/umix44.asound.conf ~/.asoundrc
         echo -e “Setting output levels to maximum:\n”
         python /usr/share/pideck/touchscreen_controls_L –card umix44 &
         python /usr/share/pideck/touchscreen_controls_R –card umix44 &

I have saved all this information and restarted the Pi. I get the blinking “_” and then a blank screen. Not even F10 is responsive to bring up the terminal. Right clicking my mouse suggests it is just a completely blank desktop. 

I shall reflash my Pideck 0.2 Image and start again. It certainly is frustrating, but at least I am attempting to figure out how to edit and add to the Pideck coding (I think?)

If anyone can point a Linux n00b in the right direction please I would be greatly appreciative.

Many Thanks.

Shaun.

**Comment by danielhjames** [comment]
Hi @raynessupreme the blinking underscore character on boot is normal. You should not need to reflash if you can get into the device via ssh.

If the touchscreen buttons do not appear, have you modified the `touchscreen_controls_L` and `touchscreen_controls_R` files to accept the `umix44` argument in your code? These files would need a line such as:

`if results.card == 'umix44':`

in order to recognise that argument and perform some special function. If not, you can use the generic 'twindeck' argument like so:

```
python /usr/share/pideck/touchscreen_controls_L –card twindeck &
python /usr/share/pideck/touchscreen_controls_R –card twindeck &
```
Once you have your buttons working, don't forget to check the value of `$CARDS_LINE_1` in your code as this corresponds to the first soundcard, number zero. It's fine that the Dicers are card number one.

By the way, the number on the end of each line in `sup_cards.conf` is the smallest working buffer size in milliseconds, not the channel count of the card. If 04 does not work for you when you run `/usr/share/pideck/pideck` in the terminal, try a bigger number until xwax stops complaining.

**Comment by CHLOVRL** [comment]
Hello, if I well understood, you have used the mix 44 soundcard with python? I would like to control the same sound card with python on windows to make sounds through one of the both speakers that I will choose and registered through one of the three microphones that I will connect. Have you got advises? A toolbox which I can use to do that ?
